test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,6 +4,10 @@ on:
   push:
     branches: ["main"]
 
+# OBLIGATOIRE : Donne le droit au bot de faire le "git push"
+permissions:
+  contents: write
+
 jobs:
   build-and-push:
     runs-on: ubuntu-latest
@@ -12,6 +16,7 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      # 1. Le scan qui va échouer (Exit Code 1) s'il y a des failles
       - name: Run Trivy vulnerability scanner
         uses: aquasecurity/trivy-action@master
         with:
@@ -21,24 +26,48 @@ jobs:
           exit-code: "1"
           severity: "CRITICAL,HIGH"
 
-      - name : Generate rapport in HTML files and add in the repository
-        run : |
-          trivy fs . --format table --output report.html
-          git add report.html
-          git commit -m "Rapport de scan Trivy"
-          git push
-          
+      # 2. Génération du HTML (Utilise TOUJOURS "if: always()")
+      - name: Generate HTML report
+        uses: aquasecurity/trivy-action@master
+        if: always() # LA MAGIE EST ICI : S'exécute même en cas d'Exit Code 1
+        with:
+          scan-type: "fs"
+          scan-ref: "."
+          format: "template"
+          template: "@/contrib/html.tpl" # Crée un vrai fichier HTML lisible
+          output: "report.html"
 
+      # 3. Commit et Push du rapport
+      - name: Commit and push report
+        if: always() # LA MAGIE EST ICI AUSSI
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          
+          git add report.html
+          
+          if ! git diff-index --quiet HEAD; then
+            # Le [skip ci] empêche ton push de relancer ce workflow en boucle
+            git commit -m "Ajout du rapport Trivy (HTML) [skip ci]"
+            git push
+          else
+            echo "Le rapport n'a pas changé, rien à push."
+          fi
+
+      # 4. Suite du pipeline (Ne s'exécute QUE s'il n'y a PAS eu de faille)
       - name: Set up Docker Buildx
+        if: success() # Bloque le déploiement si Trivy a trouvé une faille
         uses: docker/setup-buildx-action@v3
 
       - name: Login to Docker Hub
+        if: success()
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Build and push
+        if: success()
         uses: docker/build-push-action@v5
         with:
           context: .
@@ -47,5 +76,3 @@ jobs:
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app-backend:latest
           cache-from: type=gha
           cache-to: type=gha,mode=max
-        
-   
